--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/bae/.config/hypr/wallpaper/unixporn-disc/03.png"

-- Special
background="#282240"
foreground="#c9c7cf"
cursor="#c9c7cf"

-- Colors
color0="#282240"
color1="#4E9BFA"
color2="#689AF3"
color3="#6EAFFB"
color4="#9796B5"
color5="#93A7E6"
color6="#8DB9F8"
color7="#c9c7cf"
color8="#716c84"
color9="#4E9BFA"
color10="#689AF3"
color11="#6EAFFB"
color12="#9796B5"
color13="#93A7E6"
color14="#8DB9F8"
color15="#c9c7cf"
