# Shell variables
# Generated by 'wal'
wallpaper="/home/bae/.config/hypr/wallpaper/unixporn-disc/03.png"

# Special
background='#282240'
foreground='#c9c7cf'
cursor='#c9c7cf'

# Colors
color0='#282240'
color1='#4E9BFA'
color2='#689AF3'
color3='#6EAFFB'
color4='#9796B5'
color5='#93A7E6'
color6='#8DB9F8'
color7='#c9c7cf'
color8='#716c84'
color9='#4E9BFA'
color10='#689AF3'
color11='#6EAFFB'
color12='#9796B5'
color13='#93A7E6'
color14='#8DB9F8'
color15='#c9c7cf'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
