# Shell variables
# Generated by 'wal'
wallpaper="/home/bae/.config/hypr/wallpaper/used/155462.jpg"

# Special
background='#761727'
foreground='#dcc5c9'
cursor='#dcc5c9'

# Colors
color0='#761727'
color1='#6972F2'
color2='#D651C1'
color3='#E5A5A3'
color4='#DEC5B4'
color5='#E2C5B5'
color6='#9F9CE6'
color7='#dcc5c9'
color8='#927a7e'
color9='#6972F2'
color10='#D651C1'
color11='#E5A5A3'
color12='#DEC5B4'
color13='#E2C5B5'
color14='#9F9CE6'
color15='#dcc5c9'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
