# Shell variables
# Generated by 'wal'
wallpaper="/home/bae/.config/hypr/wallpaper/used/tokyo_pink.png"

# Special
background='#0f1016'
foreground='#c3c3c4'
cursor='#c3c3c4'

# Colors
color0='#0f1016'
color1='#5C7BB9'
color2='#A46C99'
color3='#D9769B'
color4='#EB7797'
color5='#CF7AA9'
color6='#A77DC2'
color7='#c3c3c4'
color8='#5a5a6f'
color9='#5C7BB9'
color10='#A46C99'
color11='#D9769B'
color12='#EB7797'
color13='#CF7AA9'
color14='#A77DC2'
color15='#c3c3c4'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
