[colors.primary]
background = "#0d1012"
foreground = "#c2c3c3"

[colors.cursor]
text = "#0d1012"
cursor = "#c2c3c3"

[colors.vi_mode_cursor]
text = "#0d1012"
cursor = "#c2c3c3"

[colors.search.matches]
foreground = "#0d1012"
background = "#c2c3c3"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#58656c"
background = "#c2c3c3"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#0d1012"
red = "#E7492B"
green = "#7C8472"
yellow = "#9B8C76"
blue = "#AEA68B"
magenta = "#CCB797"
cyan = "#E9DDB5"
white = "#c2c3c3"

[colors.bright]
black = "#58656c"
red = "#E7492B"
green = "#7C8472"
yellow = "#9B8C76"
blue = "#AEA68B"
magenta = "#CCB797"
cyan = "#E9DDB5"
white = "#c2c3c3"

[colors.dim]
black = "#c2c3c3"
red = "#E7492B"
green = "#CCB797"
yellow = "#9B8C76"
blue = "#AEA68B"
magenta = "#7C8472"
cyan = "#E9DDB5"
white = "#58656c"

