foreground         #c2c2c3
background         #0d0d12
background_opacity 1.0
cursor             #c2c2c3

active_tab_foreground     #0d0d12
active_tab_background     #c2c2c3
inactive_tab_foreground   #c2c2c3
inactive_tab_background   #0d0d12

active_border_color   #c2c2c3
inactive_border_color #0d0d12
bell_border_color     #684D60

color0       #0d0d12
color8       #58586c
color1       #684D60
color9       #684D60
color2       #B4726C
color10      #B4726C
color3       #546E94
color11      #546E94
color4       #9674A1
color12      #9674A1
color5       #F3758D
color13      #F3758D
color6       #43B1DB
color14      #43B1DB
color7       #c2c2c3
color15      #c2c2c3
