--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/bae/.config/hypr/wallpaper/used/x028Muk.png"

-- Special
background="#12111b"
foreground="#c3c3c6"
cursor="#c3c3c6"

-- Colors
color0="#12111b"
color1="#63627C"
color2="#586C87"
color3="#6B6A84"
color4="#BC7592"
color5="#7D84A0"
color6="#D99C9B"
color7="#c3c3c6"
color8="#5c5c71"
color9="#63627C"
color10="#586C87"
color11="#6B6A84"
color12="#BC7592"
color13="#7D84A0"
color14="#D99C9B"
color15="#c3c3c6"
