# Shell variables
# Generated by 'wal'
wallpaper="/home/bae/.config/hypr/wallpaper/used/x028Muk.png"

# Special
background='#12111b'
foreground='#c3c3c6'
cursor='#c3c3c6'

# Colors
color0='#12111b'
color1='#63627C'
color2='#586C87'
color3='#6B6A84'
color4='#BC7592'
color5='#7D84A0'
color6='#D99C9B'
color7='#c3c3c6'
color8='#5c5c71'
color9='#63627C'
color10='#586C87'
color11='#6B6A84'
color12='#BC7592'
color13='#7D84A0'
color14='#D99C9B'
color15='#c3c3c6'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
