#0d0d12

$foreground = rgb(c2c2c3)
$background = rgb(0d0d12)
$wallpaper = rgb(home/bae/.config/hypr/wallpaper/used/04.png)

$color0 = rgb(0d0d12)
$color1 = rgb(684D60)
$color2 = rgb(B4726C)
$color3 = rgb(546E94)
$color4 = rgb(9674A1)
$color5 = rgb(F3758D)
$color6 = rgb(43B1DB)
$color7 = rgb(c2c2c3)
$color8 = rgb(58586c)
$color9 = rgb(684D60)
$color10 = rgb(B4726C)
$color11 = rgb(546E94)
$color12 = rgb(9674A1)
$color13 = rgb(F3758D)
$color14 = rgb(43B1DB)
$color15 = rgb(c2c2c3)