#761727

$foreground = rgb(dcc5c9)
$background = rgb(761727)
$wallpaper = rgb(home/bae/.config/hypr/wallpaper/used/155462.jpg)

$color0 = rgb(761727)
$color1 = rgb(6972F2)
$color2 = rgb(D651C1)
$color3 = rgb(E5A5A3)
$color4 = rgb(DEC5B4)
$color5 = rgb(E2C5B5)
$color6 = rgb(9F9CE6)
$color7 = rgb(dcc5c9)
$color8 = rgb(927a7e)
$color9 = rgb(6972F2)
$color10 = rgb(D651C1)
$color11 = rgb(E5A5A3)
$color12 = rgb(DEC5B4)
$color13 = rgb(E2C5B5)
$color14 = rgb(9F9CE6)
$color15 = rgb(dcc5c9)