[colors.primary]
background = "#12111b"
foreground = "#c3c3c6"

[colors.cursor]
text = "#12111b"
cursor = "#c3c3c6"

[colors.vi_mode_cursor]
text = "#12111b"
cursor = "#c3c3c6"

[colors.search.matches]
foreground = "#12111b"
background = "#c3c3c6"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#5c5c71"
background = "#c3c3c6"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#12111b"
red = "#63627C"
green = "#586C87"
yellow = "#6B6A84"
blue = "#BC7592"
magenta = "#7D84A0"
cyan = "#D99C9B"
white = "#c3c3c6"

[colors.bright]
black = "#5c5c71"
red = "#63627C"
green = "#586C87"
yellow = "#6B6A84"
blue = "#BC7592"
magenta = "#7D84A0"
cyan = "#D99C9B"
white = "#c3c3c6"

[colors.dim]
black = "#c3c3c6"
red = "#63627C"
green = "#7D84A0"
yellow = "#6B6A84"
blue = "#BC7592"
magenta = "#586C87"
cyan = "#D99C9B"
white = "#5c5c71"

