--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/bae/.config/hypr/wallpaper/used/04.png"

-- Special
background="#0d0d12"
foreground="#c2c2c3"
cursor="#c2c2c3"

-- Colors
color0="#0d0d12"
color1="#684D60"
color2="#B4726C"
color3="#546E94"
color4="#9674A1"
color5="#F3758D"
color6="#43B1DB"
color7="#c2c2c3"
color8="#58586c"
color9="#684D60"
color10="#B4726C"
color11="#546E94"
color12="#9674A1"
color13="#F3758D"
color14="#43B1DB"
color15="#c2c2c3"
