[colors.primary]
background = "#761727"
foreground = "#dcc5c9"

[colors.cursor]
text = "#761727"
cursor = "#dcc5c9"

[colors.vi_mode_cursor]
text = "#761727"
cursor = "#dcc5c9"

[colors.search.matches]
foreground = "#761727"
background = "#dcc5c9"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#927a7e"
background = "#dcc5c9"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#761727"
red = "#6972F2"
green = "#D651C1"
yellow = "#E5A5A3"
blue = "#DEC5B4"
magenta = "#E2C5B5"
cyan = "#9F9CE6"
white = "#dcc5c9"

[colors.bright]
black = "#927a7e"
red = "#6972F2"
green = "#D651C1"
yellow = "#E5A5A3"
blue = "#DEC5B4"
magenta = "#E2C5B5"
cyan = "#9F9CE6"
white = "#dcc5c9"

[colors.dim]
black = "#dcc5c9"
red = "#6972F2"
green = "#E2C5B5"
yellow = "#E5A5A3"
blue = "#DEC5B4"
magenta = "#D651C1"
cyan = "#9F9CE6"
white = "#927a7e"

