# Shell variables
# Generated by 'wal'
wallpaper="/home/bae/.config/hypr/wallpaper/used/04.png"

# Special
background='#0d0d12'
foreground='#c2c2c3'
cursor='#c2c2c3'

# Colors
color0='#0d0d12'
color1='#684D60'
color2='#B4726C'
color3='#546E94'
color4='#9674A1'
color5='#F3758D'
color6='#43B1DB'
color7='#c2c2c3'
color8='#58586c'
color9='#684D60'
color10='#B4726C'
color11='#546E94'
color12='#9674A1'
color13='#F3758D'
color14='#43B1DB'
color15='#c2c2c3'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
