#12111b

$foreground = rgb(c3c3c6)
$background = rgb(12111b)
$wallpaper = rgb(home/bae/.config/hypr/wallpaper/used/x028Muk.png)

$color0 = rgb(12111b)
$color1 = rgb(63627C)
$color2 = rgb(586C87)
$color3 = rgb(6B6A84)
$color4 = rgb(BC7592)
$color5 = rgb(7D84A0)
$color6 = rgb(D99C9B)
$color7 = rgb(c3c3c6)
$color8 = rgb(5c5c71)
$color9 = rgb(63627C)
$color10 = rgb(586C87)
$color11 = rgb(6B6A84)
$color12 = rgb(BC7592)
$color13 = rgb(7D84A0)
$color14 = rgb(D99C9B)
$color15 = rgb(c3c3c6)