--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/bae/.config/hypr/wallpaper/Dandadan/00.png"

-- Special
background="#0d1012"
foreground="#c2c3c3"
cursor="#c2c3c3"

-- Colors
color0="#0d1012"
color1="#E7492B"
color2="#7C8472"
color3="#9B8C76"
color4="#AEA68B"
color5="#CCB797"
color6="#E9DDB5"
color7="#c2c3c3"
color8="#58656c"
color9="#E7492B"
color10="#7C8472"
color11="#9B8C76"
color12="#AEA68B"
color13="#CCB797"
color14="#E9DDB5"
color15="#c2c3c3"
