# Shell variables
# Generated by 'wal'
wallpaper="/home/bae/.config/hypr/wallpaper/Dandadan/00.png"

# Special
background='#0d1012'
foreground='#c2c3c3'
cursor='#c2c3c3'

# Colors
color0='#0d1012'
color1='#E7492B'
color2='#7C8472'
color3='#9B8C76'
color4='#AEA68B'
color5='#CCB797'
color6='#E9DDB5'
color7='#c2c3c3'
color8='#58656c'
color9='#E7492B'
color10='#7C8472'
color11='#9B8C76'
color12='#AEA68B'
color13='#CCB797'
color14='#E9DDB5'
color15='#c2c3c3'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
