#0d1012

$foreground = rgb(c2c3c3)
$background = rgb(0d1012)
$wallpaper = rgb(home/bae/.config/hypr/wallpaper/Dandadan/00.png)

$color0 = rgb(0d1012)
$color1 = rgb(E7492B)
$color2 = rgb(7C8472)
$color3 = rgb(9B8C76)
$color4 = rgb(AEA68B)
$color5 = rgb(CCB797)
$color6 = rgb(E9DDB5)
$color7 = rgb(c2c3c3)
$color8 = rgb(58656c)
$color9 = rgb(E7492B)
$color10 = rgb(7C8472)
$color11 = rgb(9B8C76)
$color12 = rgb(AEA68B)
$color13 = rgb(CCB797)
$color14 = rgb(E9DDB5)
$color15 = rgb(c2c3c3)