--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/bae/.config/hypr/wallpaper/used/155462.jpg"

-- Special
background="#761727"
foreground="#dcc5c9"
cursor="#dcc5c9"

-- Colors
color0="#761727"
color1="#6972F2"
color2="#D651C1"
color3="#E5A5A3"
color4="#DEC5B4"
color5="#E2C5B5"
color6="#9F9CE6"
color7="#dcc5c9"
color8="#927a7e"
color9="#6972F2"
color10="#D651C1"
color11="#E5A5A3"
color12="#DEC5B4"
color13="#E2C5B5"
color14="#9F9CE6"
color15="#dcc5c9"
