[general]
import = ["~/.cache/wal/colors-alacritty.toml"]

[window]

opacity = 2
#opacity = 0.685

padding.x = 0
padding.y = 0

decorations = "FUll"
decorations_theme_variant = "Light" # "Dark"

[font]

normal.family = "Fira Code"
bold.family = "Fira Code"
italic.family = "Fira Code"
bold_italic.family = "Fira Code"

size = 8.0
