foreground         #c2c3c3
background         #0d1012
background_opacity 1.0
cursor             #c2c3c3

active_tab_foreground     #0d1012
active_tab_background     #c2c3c3
inactive_tab_foreground   #c2c3c3
inactive_tab_background   #0d1012

active_border_color   #c2c3c3
inactive_border_color #0d1012
bell_border_color     #E7492B

color0       #0d1012
color8       #58656c
color1       #E7492B
color9       #E7492B
color2       #7C8472
color10      #7C8472
color3       #9B8C76
color11      #9B8C76
color4       #AEA68B
color12      #AEA68B
color5       #CCB797
color13      #CCB797
color6       #E9DDB5
color14      #E9DDB5
color7       #c2c3c3
color15      #c2c3c3
