#0f1016

$foreground = rgb(c3c3c4)
$background = rgb(0f1016)
$wallpaper = rgb(home/bae/.config/hypr/wallpaper/used/tokyo_pink.png)

$color0 = rgb(0f1016)
$color1 = rgb(5C7BB9)
$color2 = rgb(A46C99)
$color3 = rgb(D9769B)
$color4 = rgb(EB7797)
$color5 = rgb(CF7AA9)
$color6 = rgb(A77DC2)
$color7 = rgb(c3c3c4)
$color8 = rgb(5a5a6f)
$color9 = rgb(5C7BB9)
$color10 = rgb(A46C99)
$color11 = rgb(D9769B)
$color12 = rgb(EB7797)
$color13 = rgb(CF7AA9)
$color14 = rgb(A77DC2)
$color15 = rgb(c3c3c4)